name: "Sanity Check"
on:
  push:
    branches:
      - "main"
jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: .
        with:
          username: "tianhaoz95"
          email: "tianhaoz@umich.edu"
          token: ${{ secrets.TIANHAOZ_GITHUB_TOKEN }}
          config_files: "actions/file-dup-action/example_config.json"
          method: "dry_run"