name: "Maybe push Setup GH CLI action"
on:
  push:
    branches:
      - "master"
    paths:
      - "projects/infra/github/actions/setup-gh-cli/**"
      - ".github/workflows/infra__github__actions__maybe-push-setup-gh-cli-action.yml"
  pull_request:
    branches:
      - "master"
    paths:
      - "projects/infra/github/actions/setup-gh-cli/**"
      - ".github/workflows/infra__github__actions__maybe-push-setup-gh-cli-action.yml"
jobs:
  maybe-push-setup-gh-cli-action:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/infra/github/actions/setup-gh-cli
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm install -g lerna && lerna bootstrap
      - uses: ./projects/infra/github/actions/setup-gh-cli
        with:
          token: ${{ secrets.TIANHAOZ_GITHUB_TOKEN }}
      - name: try gh commands
        run: gh issue list
      - uses: cpina/github-action-push-to-another-repository@master
        if: ${{ github.event_name == 'push' }}
        env:
          API_TOKEN_GITHUB: ${{ secrets.TIANHAOZ_GITHUB_TOKEN }}
        with:
          source-directory: "actions/setup-gh-cli"
          destination-repository-username: "Monorepo-Actions"
          destination-github-username: "tianhaoz95"
          destination-repository-name: "setup-gh-cli"
          target-branch: "main"
          user-email: "tianhaoz@umich.edu"
